name: Compile and Test
description: Compile and test the dr-socket extension

inputs:
  dr-socket-path:
    type: string
    description: Checked out path of dr-socket
    required: true
  compile-command:
    type: string
    description: Compile command
    required: true
  artifact-name:
    type: string
    description: Name of the saved artifact
    required: true

runs:
  using: "composite"
  steps:
    - uses: kfischer-okarin/download-dragonruby@v1
      with:
        license_tier: pro
    - name: Compile
      run: |
        ${{ inputs.compile-command }}
        mv native $GITHUB_WORKSPACE/native
      working-directory: ${{ inputs.dr-socket-path }}
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: native/
